# Generated by Django 4.1.3 on 2022-11-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente'), ('Faturista', 'Faturista')], max_length=100, verbose_name='Cargo')),
            ],
        ),
    ]
