# Generated by Django 4.1.3 on 2022-11-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salario'),
            preserve_default=False,
        ),
    ]
