# Generated by Django 4.1.3 on 2022-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_funcionario_salario_cargo_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente'), ('Faturista', 'Faturista')], max_length=100, verbose_name='Cargo'),
        ),
    ]
