# Generated by Django 4.1.3 on 2022-11-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
