# Generated by Django 4.1.3 on 2022-11-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_billingprofile_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofile',
            options={'verbose_name': 'Perfil de cobrança', 'verbose_name_plural': 'Perfis de cobrança'},
        ),
    ]
