# Generated by Django 4.1.3 on 2022-11-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cart_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
    ]
