# Generated by Django 4.1.3 on 2022-11-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
    ]
