# Generated by Django 4.1.3 on 2022-11-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_guestemail_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestemail',
            options={'verbose_name': 'e-mail de convidado', 'verbose_name_plural': 'e-mails de convidados'},
        ),
    ]
