# Generated by Django 4.1.3 on 2022-11-26 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_acompanharpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 10, 13, 43, 369931)),
        ),
    ]
