# Generated by Django 4.1.3 on 2022-11-26 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_data_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 50, 5, 431246)),
        ),
    ]
