# Generated by Django 4.1.3 on 2022-11-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_technicalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=0, max_length=120, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=0, max_length=120, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(max_length=120, verbose_name='Tipo'),
        ),
    ]
