# Generated by Django 4.1.3 on 2022-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_brand_product_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Controle', 'Controle'), ('Headset', 'Headset'), ('Monitor', 'Monitor'), ('Caixa de som', 'Caixa de som')], max_length=100, verbose_name='Tipo de produto'),
        ),
    ]
